codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 5%
        informational: true
    patch:
      default:
        target: auto
        threshold: 5%
        informational: true

comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: false

# Paths to ignore from coverage reports
# These patterns exclude entire directories from coverage analysis
ignore:
  - "test/**"
  - "benchmark/**"
  - "build/**"
  - "docs/**"
  - "**/*.md"

# Define coverage components for better organization
component_management:
  default_rules:
    statuses:
      - type: project
        informational: true
      - type: patch
        informational: true
  individual_components:
    - component_id: library
      name: Library Code
      paths:
        - src/**
        - include/**

# Coverage flags for different instrumentation methods
# See docs/coverage.md for details on the differences between gcov and llvm
flags:
  gcov:
    # GCC/gcov-based coverage (traditional approach)
    # Note: Has known limitations with header file attribution.
    # Template and inline code may be attributed to .cpp files instead of headers.
    paths:
      - src/
      - include/
    carryforward: true

  llvm:
    # Clang/llvm-cov source-based coverage
    # Provides accurate header file coverage attribution.
    # Template and inline code is correctly attributed to header files.
    paths:
      - src/
      - include/
    carryforward: true

  python:
    # Python source coverage (pytest-cov)
    # Note: Only measures Python code (__init__.py). Type stub files (.pyi)
    # contain no executable code and cannot be measured by coverage tools.
    paths:
      - python/src/vroom_csv/
    carryforward: true

  python-bindings:
    # C++ bindings coverage (llvm-cov)
    # Measures bindings.cpp - the pybind11 extension module code.
    # Uses LLVM source-based coverage for accurate attribution.
    paths:
      - python/src/
    carryforward: true
