# Generated by cpp11: do not edit by hand

vroom_convert <- function(x) {
  .Call(`_vroom_vroom_convert`, x)
}

vroom_materialize <- function(x, replace) {
  .Call(`_vroom_vroom_materialize`, x, replace)
}

vroom_str_ <- function(x) {
  .Call(`_vroom_vroom_str_`, x)
}

gen_character_ <- function(n, min, max, values, seed, seed2) {
  .Call(`_vroom_gen_character_`, n, min, max, values, seed, seed2)
}

guess_type_ <- function(input, na, locale, guess_integer) {
  .Call(`_vroom_guess_type_`, input, na, locale, guess_integer)
}

convert_connection <- function(in_con, out_con, from, to) {
  .Call(`_vroom_convert_connection`, in_con, out_con, from, to)
}

vroom_arrow_ <- function(path, delim, quote, has_header, skip, comment, skip_empty_rows, na_values, num_threads) {
  .Call(`_vroom_vroom_arrow_`, path, delim, quote, has_header, skip, comment, skip_empty_rows, na_values, num_threads)
}

vroom_libvroom_fwf_ <- function(input, col_starts, col_ends, col_names, trim_ws, comment, skip_empty_rows, na_values, skip, n_max, num_threads, col_types, col_type_names) {
  .Call(`_vroom_vroom_libvroom_fwf_`, input, col_starts, col_ends, col_names, trim_ws, comment, skip_empty_rows, na_values, skip, n_max, num_threads, col_types, col_type_names)
}

vroom_lines_libvroom_ <- function(input, skip, n_max, na_values, skip_empty_rows, num_threads, use_altrep) {
  .Call(`_vroom_vroom_lines_libvroom_`, input, skip, n_max, na_values, skip_empty_rows, num_threads, use_altrep)
}

vroom_libvroom_ <- function(input, delim, quote, has_header, skip, comment, skip_empty_rows, trim_ws, na_values, num_threads, strings_as_factors, use_altrep, col_types, col_type_names, default_col_type, escape_backslash) {
  .Call(`_vroom_vroom_libvroom_`, input, delim, quote, has_header, skip, comment, skip_empty_rows, trim_ws, na_values, num_threads, strings_as_factors, use_altrep, col_types, col_type_names, default_col_type, escape_backslash)
}

has_trailing_newline <- function(filename) {
  .Call(`_vroom_has_trailing_newline`, filename)
}

utctime_ <- function(year, month, day, hour, min, sec, psec) {
  .Call(`_vroom_utctime_`, year, month, day, hour, min, sec, psec)
}

whitespace_columns_ <- function(filename, skip, n, comment) {
  .Call(`_vroom_whitespace_columns_`, filename, skip, n, comment)
}

parse_datetime_ <- function(x, format, locale) {
  .Call(`_vroom_parse_datetime_`, x, format, locale)
}

parse_date_ <- function(x, format, locale) {
  .Call(`_vroom_parse_date_`, x, format, locale)
}

parse_time_ <- function(x, format, locale) {
  .Call(`_vroom_parse_time_`, x, format, locale)
}

vroom_write_ <- function(input, filename, delim, eol, na_str, col_names, append, options, num_threads, progress, buf_lines) {
  invisible(.Call(`_vroom_vroom_write_`, input, filename, delim, eol, na_str, col_names, append, options, num_threads, progress, buf_lines))
}

vroom_write_connection_ <- function(input, con, delim, eol, na_str, col_names, options, num_threads, progress, buf_lines, is_stdout, append) {
  invisible(.Call(`_vroom_vroom_write_connection_`, input, con, delim, eol, na_str, col_names, options, num_threads, progress, buf_lines, is_stdout, append))
}

vroom_format_ <- function(input, delim, eol, na_str, col_names, append, options, num_threads, progress, buf_lines) {
  .Call(`_vroom_vroom_format_`, input, delim, eol, na_str, col_names, append, options, num_threads, progress, buf_lines)
}
