# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

force_materialization <- function(x) {
    invisible(.Call(`_vroom_force_materialization`, x))
}

vroom_materialize <- function(x) {
    invisible(.Call(`_vroom_vroom_materialize`, x))
}

vroom_str_ <- function(x) {
    .Call(`_vroom_vroom_str_`, x)
}

gen_character_ <- function(n, min, max, values) {
    .Call(`_vroom_gen_character_`, n, min, max, values)
}

guess_type_ <- function(input, locale, guess_integer = FALSE) {
    .Call(`_vroom_guess_type_`, input, locale, guess_integer)
}

vroom_ <- function(inputs, delim, quote, trim_ws, escape_double, escape_backslash, comment, skip, n_max, progress, col_names, col_types, col_select, id, na, locale, guess_max, num_threads, altrep_opts) {
    .Call(`_vroom_vroom_`, inputs, delim, quote, trim_ws, escape_double, escape_backslash, comment, skip, n_max, progress, col_names, col_types, col_select, id, na, locale, guess_max, num_threads, altrep_opts)
}

vroom_fwf_ <- function(inputs, col_starts, col_ends, trim_ws, col_names, col_types, col_select, skip, comment, n_max, id, na, locale, guess_max, num_threads, altrep_opts, progress) {
    .Call(`_vroom_vroom_fwf_`, inputs, col_starts, col_ends, trim_ws, col_names, col_types, col_select, skip, comment, n_max, id, na, locale, guess_max, num_threads, altrep_opts, progress)
}

whitespace_columns_ <- function(filename, skip, n = 100L, comment = "") {
    .Call(`_vroom_whitespace_columns_`, filename, skip, n, comment)
}

vroom_write_ <- function(input, filename, delim, col_names, buf_lines, num_threads) {
    invisible(.Call(`_vroom_vroom_write_`, input, filename, delim, col_names, buf_lines, num_threads))
}

vroom_format_ <- function(input, delim, col_names) {
    .Call(`_vroom_vroom_format_`, input, delim, col_names)
}

